 
% Enter your KB below this line:
pick_restaurant(anandam) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [vegetarian,indian]), payment(Pay), memberOfPay(Pay , [card]), price(Price), smallerThan(150, Price), rating(Rating), smallerThan(Rating,3.6), distance(Distance), smallerThan(2.5, Distance). 
pick_restaurant(mainland_china) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [chinese, seafood]), payment(Pay), memberOfPay(Pay , [card,cash]), price(Price), smallerThan(400, Price), rating(Rating), smallerThan(Rating,3.7), distance(Distance), smallerThan(1.6, Distance). 
pick_restaurant(burger_king) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [fast_food, burger]), payment(Pay), memberOfPay(Pay , [cash,card]), price(Price), smallerThan(200, Price), rating(Rating), smallerThan(Rating,3.6), distance(Distance), smallerThan(4.7, Distance). 
pick_restaurant(kfc) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [fast_food, burger]), payment(Pay), memberOfPay(Pay , [cash]), price(Price), smallerThan(200, Price), rating(Rating), smallerThan(Rating,3.7), distance(Distance), smallerThan(3.1, Distance). 
pick_restaurant(dominos_pizza) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [fast_food, pizza]), payment(Pay), memberOfPay(Pay , [cash,card]), price(Price), smallerThan(300, Price), rating(Rating), smallerThan(Rating,3.7), distance(Distance), smallerThan(1.9, Distance). 
pick_restaurant(karachi_cafe) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [cafe]), payment(Pay), memberOfPay(Pay , [card]), price(Price), smallerThan(250, Price), rating(Rating), smallerThan(Rating,4.0), distance(Distance), smallerThan(3.3, Distance). 
pick_restaurant(whiteboard_cafe) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [vegetarian,cafe]), payment(Pay), memberOfPay(Pay , [cash,card]), price(Price), smallerThan(250, Price), rating(Rating), smallerThan(Rating,3.9), distance(Distance), smallerThan(2.5, Distance). 
pick_restaurant(firangi_bake) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [italian,mexican]), payment(Pay), memberOfPay(Pay , [cash,card]), price(Price), smallerThan(250, Price), rating(Rating), smallerThan(Rating,3.6), distance(Distance), smallerThan(2.9, Distance). 
pick_restaurant(little_italy) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [vegetarian,italian,continental]), payment(Pay), memberOfPay(Pay , [cash,card]), price(Price), smallerThan(750, Price), rating(Rating), smallerThan(Rating,3.6), distance(Distance), smallerThan(2.2, Distance). 
pick_restaurant(mamagoto) :- cuisine(Cuisine),  memberOfCuisine(Cuisine , [asian]), payment(Pay), memberOfPay(Pay , [cash,card]), price(Price), smallerThan(600, Price), rating(Rating), smallerThan(Rating,4.3), distance(Distance), smallerThan(1.0, Distance). 
pick_restaurant(urban_asia) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [asian]), payment(Pay), memberOfPay(Pay , [cash,card]), price(Price), smallerThan(450, Price), rating(Rating), smallerThan(Rating,4.2), distance(Distance), smallerThan(9.0, Distance). 
pick_restaurant(hitec_nanking) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [chinese]), payment(Pay), memberOfPay(Pay , [cash,card]), price(Price), smallerThan(350, Price), rating(Rating), smallerThan(Rating,3.7), distance(Distance), smallerThan(3.7, Distance). 
pick_restaurant(grill_box) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [mediterranean]), price(Price), memberOfPay(Pay , [cash,card]), payment(Pay), smallerThan(200, Price), rating(Rating), smallerThan(Rating,2.7), distance(Distance), smallerThan(4.2, Distance). 
pick_restaurant(freshies_gourmet_salad) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [healthy_food, salad]), payment(Pay), memberOfPay(Pay , [cash]), price(Price), smallerThan(250, Price), rating(Rating), smallerThan(Rating,3.4), distance(Distance), smallerThan(2.8, Distance). 
pick_restaurant(mustang_terrace_lodge) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [mexican,italian,salad,indian]), payment(Pay), memberOfPay(Pay , [cash]), price(Price), smallerThan(550, Price), rating(Rating), smallerThan(Rating,3.9), distance(Distance), smallerThan(3.9, Distance). 
pick_restaurant(india_bistro) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [indian]), payment(Pay), memberOfPay(Pay , [cash,card]), price(Price), smallerThan(500, Price), rating(Rating), smallerThan(Rating,4.5), distance(Distance), smallerThan(1.4, Distance). 
pick_restaurant(drunken_monkey) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [healthy_food]), payment(Pay), memberOfPay(Pay , [cash,card]), price(Price), smallerThan(200, Price), rating(Rating), smallerThan(Rating,4.0), distance(Distance), smallerThan(3.0, Distance). 
pick_restaurant(wich_please) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [fast_food]), payment(Pay), memberOfPay(Pay , [card]), price(Price), smallerThan(100, Price), rating(Rating), smallerThan(Rating,3.6), distance(Distance), smallerThan(2.9, Distance). 
pick_restaurant(punjabi_bytes) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [indian]), payment(Pay), memberOfPay(Pay , [cash]), price(Price), smallerThan(100, Price), rating(Rating), smallerThan(Rating,3.7), distance(Distance), smallerThan(2.7, Distance). 
pick_restaurant(holi_restaurant) :-  cuisine(Cuisine), memberOfCuisine(Cuisine , [indian,chinese]), payment(Pay), memberOfPay(Pay , [cash,card]), price(Price), smallerThan(400, Price), rating(Rating), smallerThan(Rating,2.5), distance(Distance), smallerThan(0.8, Distance). 
memberOfCuisine([Xh|Xt], Y) :- member(Xh,Y), (length(Xt,0) -> !; memberOfCuisine(Xt, Y)). 
memberOfPay([H|T], P) :- member(H,P); memberOfPay(T,P). 
smallerThan(X,Y) :- X =< Y.
